### ISSUE TITLE
don't work With esp8266

### ISSUE THREAD

**Issue by karlTH** [Seeed-Studio/Grove_LCD_RGB_Backlight#10]
Hello,
is it possible to make work this library with the esp8266.

and in general is it possible to make work the grove module with the esp8266.
(evoluate module not the analogique and numerique who already work)

thanks a lot

**Comment by KillingJacky** [comment]
This Grove only works under 5V. It's not compatible with the voltage level of ESP.

**Comment by karlTH** [comment]
Thanks for you're answer

**Comment by pixshatterer** [comment]
It works if you have a module like the LoLin which has a `VU` pin, which provides 5V

**Comment by KillingJacky** [comment]
Will close this issue, please open a new issue if you have further questions.
