### ISSUE TITLE
Display Showing RBG Colors and Text Values

### ISSUE THREAD

**Issue by netlander** [Seeed-Studio/Grove_LCD_RGB_Backlight#12]
When I connect the display to Grove Shield V2 and run any one of the examples the display briefly shows output from example then switches to fading between various RBG colors and text values of those RGB colors.

Is this a faulty unit?

**Comment by Pillar1989** [comment]
Is this problem solved? How can I help you?

**Comment by netlander** [comment]
I think it's fault with the display. Sometimes it just works and other times it flickers with RGB colours.

**Comment by Pillar1989** [comment]
Then I will close the issue first, and you can continue to open the issues later, if you need to discuss
