### ISSUE TITLE
no noBacklight() function ?

### ISSUE THREAD

**Issue by Jimbo-77** [Seeed-Studio/Grove_LCD_RGB_Backlight#13]
Hi,

I'm surprised not to see a noBacklight() function. It will be nice to have this feature.

regards,

Jim

**Comment by Pillar1989** [comment]
Does this function not work?
https://github.com/Seeed-Studio/Grove_LCD_RGB_Backlight/blob/master/rgb_lcd.h#L140

**Comment by Kodar-le-dok** [comment]
I would rather use the following block, to avoid any blinking issue:
```
lcd.setPWM(REG_RED, 0);
lcd.setPWM(REG_GREEN, 0);
lcd.setPWM(REG_BLUE, 0);
```
