### ISSUE TITLE
lcd.print("Hello world") not printing anything?

### ISSUE THREAD

**Issue by romain130492** [Seeed-Studio/Grove_LCD_RGB_Backlight#15]
Hey

i cannot make that simple hello world file to work,,

```
#include <Wire.h>
#include "rgb_lcd.h"

rgb_lcd lcd;

const int colorR = 255;
const int colorG = 0;
const int colorB = 0;

void setup() {
    // set up the LCD's number of columns and rows:
    lcd.begin(16, 2);

    lcd.setRGB(colorR, colorG, colorB);

    // Print a message to the LCD.
    lcd.print("hello, world!");

    delay(1000);
}

void loop() {
    // set the cursor to column 0, line 1
    // (note: line 1 is the second row, since counting begins with 0):
    lcd.setCursor(0, 1);
    // print the number of seconds since reset:
    lcd.print(millis() / 1000);

    delay(100);
}


```

<img width="684" alt="Screen Shot 2021-12-17 at 10 09 01 PM" src="https://user-images.githubusercontent.com/57079606/146556655-1231882d-3dcb-424c-a211-e6fddffa50d8.png">

**Comment by dsssssssss9** [comment]
Hi 

From your photo it looks like you have in plugged into the wrong port ....

Could you please try by connecting it to one of the ports marked I2C ( with the power off )  & see if that works for you ?

Hope this helps 

J

**Comment by dsssssssss9** [comment]
This display is 5v only I believe..

From your picture it appears that you have the  VCC switch set to 3.3V ? 

If this is the case , could you please power off & move the VCC switch to the 5V position . Power up & try again .

Hope this helps ?

**Comment by CptHolzschnauz** [comment]
Uno R4 is not compatible IMHO

**Comment by ackPeng** [comment]
@romain130492 Did you solve this problem? Do you have any questions?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
