### ISSUE TITLE
Extra pixel in the smiley in CustomCharacter.ino

### ISSUE THREAD

**Issue by Kodar-le-dok** [Seeed-Studio/Grove_LCD_RGB_Backlight#18]
While testing the CustomCharacter.ino example, there is an extra pixel that appears above the left eye of the smiley, whatever the changes I have tried to make. (see attached picture just below)
![IMG_20220504_145237](https://user-images.githubusercontent.com/22836943/166685460-514df716-feb5-42d3-8a2a-4a34a6881f5a.jpg)
I just cannot understand why, since the definition for that character is the following:
```
byte smiley[8] = {
    0b00000,
    0b00000,
    0b01010,
    0b00000,
    0b00000,
    0b10001,
    0b01110,
    0b00000
};
```
Could you explain why this happens and, hopefully, give some way to remove this extra pixel?

**Comment by lakshanthad** [comment]
Hello,

What is the microcontroller board you are using?

**Comment by lakshanthad** [comment]
Hello,

I will test this and get back to you.

**Comment by lakshanthad** [comment]
Hello,

I have tested the same "CustomCharacter.ino example"  with my Arduino UNO board and it worked well. There was no extra pixel.

Could you please share a photo of your hardware connection?

Thank you.

**Comment by ackPeng** [comment]
@Kodar-le-dok Hi, do you have any questions about this?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
