### ISSUE TITLE
Extra character at the end of the display in SerialDisplay.ino

### ISSUE THREAD

**Issue by Kodar-le-dok** [Seeed-Studio/Grove_LCD_RGB_Backlight#19]
While testing the SerialDisplay.ino example, after any string I would send to the display through the serial monitor, some extra character is added at the end (see picture attached right below).

![IMG_20220504_152319](https://user-images.githubusercontent.com/22836943/166690931-8fe08584-30fd-4236-ac35-be1b424dd417.jpg)

By the way, if I upload the CustomCharacter.ino example beforehand, this extra character appears to be exactly the same one as the frownie character, if that can help. My guess is that this extra character comes from some memory space at a specific address of the Arduino card.
Can you help on how to remove this extra character from the LCD display?

**Comment by lakshanthad** [comment]
Hello,

What is the microcontroller board you are using?

**Comment by Kodar-le-dok** [comment]
Hello.
The Arduino card is a Genuino 101 one.

**Comment by lakshanthad** [comment]
Hello,

I will test this and get back to you.

**Comment by lakshanthad** [comment]
Hello,

I have tested the same "SerialDisplay.ino example"  with my Arduino UNO board and it worked well. There was no extra character displayed.

Could you please share a photo of your hardware connection?

Thank you.
