### ISSUE TITLE
12c does not connect with arduino uno r4 wifi

### ISSUE THREAD

**Issue by jessewriter** [Seeed-Studio/Grove_LCD_RGB_Backlight#25]
example scripts like 'hello world' run on my other devices but not when paired with the arduino uno r4 wifi.  no power going to the lcd rgb backlight display by grove.  i believe the pin connections are different see https://docs.arduino.cc/tutorials/uno-r4-minima/shield-guide see sda scl locations

**Comment by CptHolzschnauz** [comment]
Confirm

**Comment by ackPeng** [comment]
Thank you very much for your discussion. If there are no other questions, this discussion will be closed. If you have any suggestions or questions, please feel free to contact us.
