### ISSUE TITLE
Display stabillization

### ISSUE THREAD

**Issue by SCKelemen** [Seeed-Studio/Grove_LCD_RGB_Backlight#7]
Writing to the display quickly, multiple times, causes the screen to render very lightly, as it continuously updates. Is there a best practices for writing to the display in a more stable manner? I am using the display to show the pitch, yaw, and roll of a IMU.

**Comment by jsilence** [comment]
I have the same problem that the text is displayed very light, even when not writing frequently.

**Comment by awong1900** [comment]
@jsilence Can you provide any code to generate this phenomenon? Or some image. I have no image for this.

**Comment by jsilence** [comment]
The display had been connected to a Grove shield which was set to 3V. Flipping the switch on the Grove shield to 5V resolved the issue for me.

**Comment by awong1900** [comment]
OK we close it.
