### ISSUE TITLE
Library only supports one row

### ISSUE THREAD

**Issue by jsilence** [Seeed-Studio/Grove_LCD_RGB_Backlight#9]
The examples do not work properly. Color of the display can be set, but text does not appear.
When setting up the display as one row, the text is being displayed:
`    lcd.begin(16, 1);`
But then only one row is usable and the contrast of the displayed text is very low.

**Comment by bigkevmcd** [comment]
I ran into this issue, and I'm using the Grove shield, it was switched to 3.3v instead of 5v (there's a small switch on the side beside the reset button).

**Comment by jsilence** [comment]
Yes thank you bigkevmcd, this was it. It actually is mentioned on the wiki page of the library but that notice slipped my attention.
